### ISSUE TITLE
Second run of 'make dataset 101 2015' shows error

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#25]
```

Date: 2015-01-01

Date: 2015-02-01

Date: 2015-03-01

Date: 2015-04-01

Date: 2015-05-01

Date: 2015-06-01

Date: 2015-07-01

Calling:
mysql --database dbf_db --execute "call cfg_init_populate_dates();" 
Elapsed time: 0.24

Calling:
mysql --database dbf_db --execute "call cfg_init_regn_fullset();" 
Elapsed time: 0.17

Calling:
mysql --database dbf_db --execute "call f101_make_dataset();" 
Elapsed time: 15.47
ERROR 1062 (23000) at line 1: Duplicate entry '2015-06-01-3525-10208-840000' for key 'PRIMARY'

```

**Comment by repo2156** [comment]
This is a repeated entry according to the current primary keys. Should the set of primary keys be expanded (adding another column to differentiate the two records) or the latter entry should replace the former (or be ignored)?

**Comment by epogrebnyak** [comment]
Just ignored. Must use "INSERT IGNORE" I think.

**Comment by repo2156** [comment]
The culprit was the addition of the primary key only in the end, where the duplicates are already on the table. I've had to break the process in two, as you can see in the commit. It seems hackish, but since the created table was a view, I could not 'alter ignore' it in the stored procedure.

Previous calls to `make dataset 101 2015` resulted in the shown error, while now there are no import errors.

I've added this use of 'ignore' as a vulnerability, as it can hide bugs in the code (does not seems to be the case here, but may not be optimal for the future).
